version: '2'

volumes:
  rethinkdb:
  storage-temp:

services:
  nginx:
    build: nginx/
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - app
    networks: 
      - nius

  rethinkdb:
    image: rethinkdb:2.3
    restart: unless-stopped
    volumes:
      - rethinkdb:/data
    networks: 
      - nius
  app:
    build: app/
    restart: unless-stopped
    environment:
      - RETHINKDB_PORT_28015_TCP
      - SECRET
      - PUBLIC_IP
    depends_on:
      - rethinkdb
    volumes:
      - storage-temp:/app/data
    networks: 
      - nius

  migrate:
    image: openstf/stf:latest
    environment:
      - RETHINKDB_PORT_28015_TCP
    command: stf migrate
    depends_on:
      - rethinkdb
    networks: 
      - nius

networks: 
  nius:
    driver: bridge

  
